import type { Metadata } from "next";
import { Anonymous_Pro } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.scss";
import { Header } from "@/widgets/header/ui/Header/Header";
import { Suspense } from "react";

const anonymousPro = Anonymous_Pro({
  weight: ["400", "700"],
  style: "normal",
  variable: "--font-anonymous-pro",
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense>
      <html lang="ru">
        <body className={`${anonymousPro.variable}`}>
          <Header />
          {children}
          <ToastContainer />
        </body>
      </html>
    </Suspense>
  );
}
